FROM php:8.2-apache

# Pokud pdo_sqlite (a sqlite3) nejsou v image, doinstaluj je; jinak nic nedělej.
# Tím předejdeš chybám typu “already loaded” / “config.m4 not found” při opakovaných buildech.
RUN set -eux; \
  if ! php -m | grep -qi pdo_sqlite || ! php -m | grep -qi '^sqlite3$'; then \
    apt-get update; \
    apt-get install -y --no-install-recommends \
      $PHPIZE_DEPS \
      libsqlite3-dev \
      curl \
      iputils-ping \
    ; \
    docker-php-ext-install -j"$(nproc)" pdo_sqlite sqlite3; \
    rm -rf /var/lib/apt/lists/*; \
  fi

# (volitelně) povol mod_rewrite
RUN a2enmod rewrite
RUN a2enmod autoindex

# Povolit .htaccess (AllowOverride All) to se hodí pro vývoj, pro produkci dát pak pryč...
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf


WORKDIR /var/www/html

# storage + state (zapisovatelné)
RUN mkdir -p /var/www/storage  \
  && chown -R www-data:www-data /var/www/html  \
  && chown -R www-data:www-data /var/www/storage

# UI + proxy
COPY www/* /var/www/html/

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD curl -sf http://localhost/healthcheck.php || exit 1
