services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: solax-web
    ports:
      - "8088:80"
    environment:
      # Optional: point the proxy to store DB in /var/www/html/storage
      SLX_DB_PATH: /var/www/html/storage/solax_logs.sqlite
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    volumes:
      # --- produkce ---
      # Persist the SQLite database and any other generated artifacts
      #- solax_data:/var/www/html/storage

      # --- vývoj ---
      # Kód (HTML, PHP, JS) — živé úpravy bez rebuildů
      - ./www:/var/www/html:rw
      # SQLite databáze — přístupná i z hosta (uloží se do ./data/sqlite/ na tvém PC)
      - ./data/sqlite:/var/www/html/storage:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost/healthcheck.php || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  solax_data:
    driver: local

 # rebuild+inicializace-to je klasicky: docker compose down -v && docker compose build && docker compose up -d
   
