FROM php:8.2-apache


WORKDIR /var/www/html

# Volitelně zapnout mod_rewrite (nepotřebné pro tento basic scénář)
RUN a2enmod rewrite

RUN apt-get update && apt-get install -y iputils-ping curl \
    && rm -rf /var/lib/apt/lists/*

# Zkopíruj UI + proxy
# - *.html = tvoje HTML s JS (upravený fetch na /proxy.php)
# - proxy.php  = PHP proxy výše
COPY www/* /var/www/html/

# vytvoř zapisovatelný stav
RUN mkdir -p /var/www/html/state && chown -R www-data:www-data /var/www/html/state

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD curl -sf http://localhost/healthcheck.php || exit 1
